### ISSUE TITLE
update.zfstor.org

### ISSUE THREAD

**Issue by cron410** [zfstor/zfstor#1]
Why is this not browseable? Maybe you have some cleanup to do before opening directory listings?

**Comment by voquendo** [comment]
Any reason you need to browse it? I guess I could open directory listing but I did not see a reason to do so.

**Comment by cron410** [comment]
I wanted to cache a list of recent updates for change tracking

**Comment by voquendo** [comment]
I made http://update.zfstor.org/ZFStor/ browseable, I cannot make the root browseable because the way directories are exposed. Hopefully thats enough for you.
