### ISSUE TITLE
NAS4Free

### ISSUE THREAD

**Issue by cron410** [zfstor/zfstor#4]
Is there a reason you are not contributing to NAS4free? It seems to have the same goal as your project, but is more mature (more commits, been around longer). http://wiki.nas4free.org/doku.php  If you think zfstor differs greatly, please list reasons.

**Comment by voquendo** [comment]
My goal is to keep the codebase of 9.10 for people running FreeNAS who are not comfortable with design decisions and migration to FeeNAS 10.
